### ISSUE TITLE
Update API to the latest version (some functionality missing)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/mailchimp-plugin-for-nopcommerce#1]
Issue is described in our premium support system (ticket 13011). Requires some investigation.

**Comment by WildWolfay** [comment]
Any update on this plugin coming to 3.9?

**Comment by AndreiMaz** [comment]
We plan to update API in about two weeks

**Comment by rudgr** [comment]
any news on this? :) tx

**Comment by AndreiMaz** [comment]
@rudgr we plan to focus on third-party plugins after release of 4.00 BETA (end of September)

**Comment by rudgr** [comment]
great, tx!

**Comment by rudgr** [comment]
Hi,

Any news on this?

tx

**Comment by DmitriyKulagin** [comment]
Closed #1 ([commit](https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/commit/0cbc467bfd8249782193359c9c32d7511fe8be35))
