### ISSUE TITLE
Uninstalling plugin doesn't remove previous scheduled task

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/mailchimp-plugin-for-nopcommerce#10]
Hello, I noticed if I uninstall the plugin from nop commerce the old schedule task entry is left in the database. I noticed this when trying to upgrade from 3.9 to 4.1.

![image](https://user-images.githubusercontent.com/12185742/50406835-e3844d00-0799-11e9-8184-993ced65b35b.png)

Thanks

**Comment by cklenk** [comment]
Also in addition, it doesn't remove the old module settings as well.

**Comment by cklenk** [comment]
Also noticed with a multi store set up I get this error:

Nop.Core.NopException: Plugin is not configured
   at Nop.Plugin.Misc.MailChimp.Services.MailChimpManager.HandleRequest[T](Func`1 request)
URL: /Admin/MailChimp/Configure

It seems to keep over writing the API key and list id's when I change the store in the drop down.

**Comment by DmitriyKulagin** [comment]
The plugin must be removed with the same version as installed. We cannot maintain compatibility between different versions in this regard.
