### ISSUE TITLE
Memeber cannot be synced because TimestampSignup is not set in ISO 8601 format. 

### ISSUE THREAD

**Issue by marchrainwu** [nopSolutions/mailchimp-plugin-for-nopcommerce#11]
In MailChimpManager.cs -> CreateMemberBySubscription,  the 
TimestampSignup is not set in ISO 8601 format, which causes the member cannot be synced to Mailchimp.
      var member = new mailchimp.Member
            {
                EmailAddress = subscription.Email,
                TimestampSignup = subscription.CreatedOnUtc.ToString("s")
            };

To fix the issue, I manually format the timestamp with "yyyy-MM-ddTHH:mm:ssZ"

  var member = new mailchimp.Member
            {
                EmailAddress = subscription.Email,
                // TimestampSignup = subscription.CreatedOnUtc.ToString("s")
                TimestampSignup = subscription.CreatedOnUtc.ToString("yyyy-MM-ddTHH:mm:ssZ")
            };

**Comment by DmitriyKulagin** [comment]
Closed #11

**Comment by b1ade68** [comment]
I can see an error on each record exported (subscribtions).
`http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ - Invalid Resource - Operation createOrUpdate-subscription-139-list-e7cf893d39 - timestamp_signup - This value is not a valid datetime.;`

Please note:

1) first time (Mailchimp Audit Empty) I have 217 error on 217 subscribers. 158 Contacts are anyway imported.

2) second time I have 59 errors "timestamp_signup", but imported contacts number still remains 158, e.g. 59 contacts are not imported.

Probabily the timestamp_signup error hides some other error.

Version 4.2

**Comment by RomanovM** [comment]
The problem seems to still exist. See https://www.nopcommerce.com/boards/topic/90069/mailchimp-plugin-getting-synchronization-errors

**Comment by DmitriyKulagin** [comment]
Fixed in [this commit](https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/commit/059e7f14c9543eb9952296af77380154601f38eb)
