### ISSUE TITLE
Plugin doesn't sync active subscribers

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/mailchimp-plugin-for-nopcommerce#12]
worked good on previous versions.
In nop 4.2. synchronizes only 10 of 1270 active subscribers I have in my list.

Source: https://www.nopcommerce.com/boards/t/72823/mailchimp-plugin-doesnt-sync-active-subscribers-42.aspx

See also: https://www.nopcommerce.com/en/boards/topic/81595/mailchimp-subscribers-sync-not-working-on-42

**Comment by dissy123** [comment]
Any updates on that? 

Just tried the Plugin, the Customers are synchronised to Mailchimp, but the subscribed ones are not subscribed :/

**Comment by dissy123** [comment]
Synchronization errors:
http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ - Invalid Resource - Operation createOrUpdate-subscription-5-list-**** - SEX - Please enter a value;


Getting this error when syncing, any ideas? Something todo with that Issue?

**Comment by b1ade68** [comment]
Same problem. See my comment here https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/issues/11#issuecomment-625148478

**Comment by cklenk** [comment]
We are running this plugin on a multi site (3 stores) and get constant errors. Here is one example.

MailChimp info.
Synchronization started at: 5/11/2020 6:14:29 PM
completed at: 5/11/2020 6:14:35 PM
finished operations: 12
errored operations: 10
total operations: 12
batch ID: b5ee750f00
batch status: finished
Synchronization errors:
http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ - Method Not Allowed - Operation delete-subscription-12150-list-1d57abbe69 - This list member cannot be removed.  Please contact support.
http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ - Method Not Allowed - Operation delete-subscription-12151-list-1d57abbe69 - This list member cannot be removed.  Please contact support.
http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ - Method Not Allowed - Operation delete-subscription-12152-list-1d57abbe69 - This list member cannot be removed.  Please contact support.
http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ - Method Not Allowed - Operation delete-subscription-12150-list-25342faada - This list member cannot be removed.  Please contact support.

**Comment by cklenk** [comment]
This is another error too

Synchronization errors:
http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ - Invalid Resource - Operation createOrUpdate-subscription-12157-list-1d57abbe69 - timestamp_signup - This value is not a valid datetime.;
http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ - Invalid Resource - Operation createOrUpdate-subscription-12158-list-25342faada - timestamp_signup - This value is not a valid datetime.;

**Comment by DmitriyKulagin** [comment]
Fixed, details in commit [Changes to update plugin for 4.30](https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/commit/059e7f14c9543eb9952296af77380154601f38eb)
