### ISSUE TITLE
Sync will not finish due to large volume

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/mailchimp-plugin-for-nopcommerce#13]
nopcommerce version: 4.20

> I have almost 60,000 (more than half of which are published) products and 3 stores connected to my nopCommerce site and every time I try to run it I get a LINQ query error about 20 hours after I kick off the sync.

Source: https://www.nopcommerce.com/boards/topic/80084/mailchimp-ecommerce-sync-will-not-finish-due-to-large-volume

**Comment by DmitriyKulagin** [comment]
This problem is not directly related to the plugin and affects the implementation of some services in the kernel. We have created a separate task for this, please read the details [here](https://github.com/nopSolutions/nopCommerce/issues/4897).
