### ISSUE TITLE
Errors in mailchimp sync

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/mailchimp-plugin-for-nopcommerce#14]
version = 4.30
when we try to run mailchimp sync task manually we got this 2 errors in log 
1) _http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ - Invalid Resource - Operation createOrUpdate-customer-1781176-store-1 - email_address - An email address is required to create a customer.;_  Mostly due to guest users.
2) _http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ - Bad Request - Operation create-product-1228-store-1 - We were unable to process the request. A product with the provided ID already exists in the account_.

**Comment by jigarsangoi** [comment]
I solved 1st problem #15 
& I will monitor log for 2nd problem for next few days ( for now I m not able to regenerate )

**Comment by DmitriyKulagin** [comment]
Fixed in [this ](https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/commit/c02b7626601440922b447c52fa9df0fbab10f74b)commit.
