### ISSUE TITLE
Option to only sync subscribed customers

### ISSUE THREAD

**Issue by jbrandt-q5** [nopSolutions/mailchimp-plugin-for-nopcommerce#16]
As I understand it, MailChimp charges for the number of contacts you have not just the number of subscribed email addresses. Since I only want to use MailChimp for sending email to subscribers, it would be great if this plugin had a configuration option that ignored non-subscribed customers. It would greatly reduce monthly MailChimp costs. 

Source: https://www.nopcommerce.com/en/boards/topic/90191/mailchimp-plugin-by-nopcommerceteam

**Comment by DmitriyKulagin** [comment]
Closed #16
