### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by tonywiredin** [nopSolutions/mailchimp-plugin-for-nopcommerce#18]
The IsSynchronizationComplete method in MailChimpController attempts to use _staticCacheManager.Get which doesn't exist

Bug can be fixed by changing lone 235 to this:

`var batchesInfo = await _staticCacheManager.GetAsync(_staticCacheManager.PrepareKeyForDefaultCache(MailChimpDefaults.SynchronizationBatchesCacheKey), () => new Dictionary<string, int>());
`

**Comment by DmitriyKulagin** [comment]
@tonywiredin Thank you, we took into account your comment on this error in [this commit ](https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/commit/c02b7626601440922b447c52fa9df0fbab10f74b)
