### ISSUE TITLE
Call to Map methods not awaited

### ISSUE THREAD

**Issue by tonywiredin** [nopSolutions/mailchimp-plugin-for-nopcommerce#19]
Whilst performing a manual synch I discovered that in many places in the MailChimpManager class, the call to methods such MapStoreAsynch, MapCustomerAsync, MapProductAsync, MapOrderAsync are not called with await - this means that often, subsequent methods get called with null objects causing exceptions to be thrown.

This plugin feels like quite untested code (it doesn't even compile - see my previous issue)

**Comment by DmitriyKulagin** [comment]
@tonywiredin Thank you, we took into account your comment on this error in [this commit ](https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/commit/c02b7626601440922b447c52fa9df0fbab10f74b)
