### ISSUE TITLE
MailChimp error. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/mailchimp-plugin-for-nopcommerce#23]
> After some trapping, it seems to be in the MailChimpManager.cs unint around 576 where it's calling the Hash method.  There's no check to see if the record.Email is null.   I added the following to help prior to the has call:
> 
>                     // Verify not a null email
>                     if (record.Email == null)
>                         continue;
> 
> There's a similar call around line 525 where I did same thing:
> 
>                     // Verify not a null email
>                     if (subscription.Email == null)
>                         continue;
> 
> This seemed to resolve the object error.

Source: https://www.nopcommerce.com/boards/topic/95981/mail-chimp-plugin-for-460-error#303148

**Comment by DmitriyKulagin** [comment]
Closed #23
