### ISSUE TITLE
Not updating "Average Order Revenue" data to MailChimp

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/mailchimp-plugin-for-nopcommerce#3]
Needs investigation - http://www.nopcommerce.com/boards/t/47121/mailchimp-plugin-not-updating-average-order-revenue-data-to-mailchimp.aspx

**Comment by DmitriyKulagin** [comment]
Closed #3 ([commit](https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/commit/0cbc467bfd8249782193359c9c32d7511fe8be35))
