### ISSUE TITLE
Error while running the 'MailChimp synchronization'

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/mailchimp-plugin-for-nopcommerce#4]
System.AggregateException: One or more errors occurred. ---> System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions. ---> System.Data.Entity.Core.OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions. at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source) at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update() at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess) at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction) at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation) at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction) at System.Data.Entity.Internal.InternalContext.SaveChanges()

Deteils: [http://www.nopcommerce.com/boards/t/46596/nopcommerce-390-is-released.aspx?p=5#186995](http://www.nopcommerce.com/boards/t/46596/nopcommerce-390-is-released.aspx?p=5#186995)

**Comment by DmitriyKulagin** [comment]
Closed #4 ([commit](https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/commit/0cbc467bfd8249782193359c9c32d7511fe8be35))
