### ISSUE TITLE
An error occurred during the activation of a particular registration

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/mailchimp-plugin-for-nopcommerce#5]
See http://www.nopcommerce.com/boards/t/46997/mailchimp-synchronization-plugin-for-39.aspx#188176

**Comment by DmitriyKulagin** [comment]
Closed #5 ([commit](https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/commit/0cbc467bfd8249782193359c9c32d7511fe8be35))
