### ISSUE TITLE
eCommerce sync is not working

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/mailchimp-plugin-for-nopcommerce#8]
Source: https://www.nopcommerce.com/boards/t/54414/mailchimp-ecommerce-sync-is-not-working.aspx

**Comment by DmitriyKulagin** [comment]
Closed #8 ([commit](https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/commit/0cbc467bfd8249782193359c9c32d7511fe8be35))
